apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort # This object type is used only in the dev environment
  selector:
    component: web
  ports:
    - port: 3050 # If any other service/pod need to contact to the multi client pod, let's allow it, enabling this port
      targetPort: 3000 # The port of the container in the multi-client pod
      nodePort: 31515 # The port of this NodePort service, we can provide it or it will be randomly generated
